# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats:
  - htmlzip

build:
  os: ubuntu-24.04
  apt_packages:
    - zip
  tools:
    nodejs: "22"
  jobs:
    install:
      - cd docs && npm ci
    build:
      html:
        - cd docs && npm run build
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -r docs/.artifacts/dist/* $READTHEDOCS_OUTPUT/html/
      htmlzip:
        - cd docs && npm run build:offline
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip
        - cd docs/.artifacts && zip -r $READTHEDOCS_OUTPUT/htmlzip/phobos-offline-doc.zip phobos-offline-doc
