title: "Your new feature or enhancement title here"
labels: ["Feature / Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > **Warning**
        > Before posting a suggestion, please read the **checklist at the bottom**.

        Thanks for taking the time to submit out this feature suggestion! If you wish to discuss the feature in detail first, join us on the [C&C Mod Haven Discord](https://discord.gg/an3bDxtksM) server in the __#phobos-chat__ channel.

        Please make sure you follow these instructions and fill in every question with as much detail as possible.

        > **Note**
        > Feature requests are usually low-priority unless it's a feature that's supported by a majority of users or some developer has interest in that particular feature. Please understand that Phobos contributors work on the project for fun and are not obliged to implement every suggestion.*

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Write a detailed description of what the feature / enhancement should be and how it should function.
    validations:
      required: true

  - type: textarea
    id: ini
    attributes:
      label: INI code
      description: The suggested INI code of the feature, if applicable.
      render: ini
      value: |
        [SomeSection]
        SomeKey=SomeValue
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Attach additional files or links to content related to the feature report here (example images, gifs, videos to illustrate the suggestion etc).

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please read and ensure you followed all the following options.
      options:
        - label: The suggestion is **NOT** related to functionality of Ares, HAres, Kratos or any other YR engine extension.
          required: true
        - label: The suggested feature / enhancement is **NOT** implemented in Ares/Phobos yet and the existing possibilites are not viable or good enough to achieve the wanted result.
          required: true
        - label: I agree to elaborate the details if requested and provide thorough testing if the feature is implemented.
          required: true
        - label: I added a very descriptive title to this topic.
          required: true
        - label: I used the GitHub search and read the topic list to find a similar topic and didn't find it.
          required: true
        - label: I thought out how the feature / enhancement should work and described it in the most detailed and clear way.
          required: true
