STM_Process(this->SpySat)
STM_Process(this->BigGap)
STM_Process(this->TransactMoney)
STM_Process(this->SplashList_PickRandom)
STM_Process(this->AffectsEnemies)
STM_Process(this->CritDamage)
STM_Process(this->CritSpread)
STM_Process(this->CritChance)
STM_Process(this->CritAffects)
STM_Process(this->CritAnimsBuffer)
STM_Process(this->CritAffectsBuffer)

