#include <Utilities/Macro.h>

#include "OwnerDraw.h"

DEFINE_PATCH_TYPED(void*, 0x60FF06, WWUI::OwnerDrawWindowProc);
DEFINE_FUNCTION_JUMP(LJMP, 0x610CA0, WWUI::OwnerDrawWindowProc);
DEFINE_FUNCTION_JUMP(LJMP, 0x612B70, WWUI::OwnerDrawCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x6163A0, WWUI::CheckboxCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x616980, WWUI::RadioCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x6137D0, WWUI::TabCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x614190, WWUI::EditCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x614B30, WWUI::NewEditCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x6153E0, WWUI::StaticCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x612A60, WWUI::SysListViewCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x617250, WWUI::ComboBoxCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x618D40, WWUI::ListBoxCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x61D950, WWUI::SliderCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x61E700, WWUI::GroupBoxCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x61ECA0, WWUI::InputCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x61D6D0, WWUI::ProgressCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x61C690, WWUI::ScrollBarCtrl);
DEFINE_FUNCTION_JUMP(LJMP, 0x622B50, WWUI::OwnerDrawStandardWndProc);
