blank_issues_enabled: false
contact_links:
  - name: Official channels on C&C Mod Haven
    url: https://discord.gg/an3bDxtksM
    about: If you want to discuss something with us without filing an issue.
