name: Vanilla Bug Report
description: Open an issue to ask for a Vanilla bug to be fixed.
title: "Your bug report title here"
labels: ["Vanilla bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If you need real-time help, join us on the [C&C Mod Haven Discord](https://discord.gg/an3bDxtksM) server in the __#phobos-chat__ channel.

        Please make sure you follow these instructions and fill in every question with as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please confirm and check all the following options;
      options:
        - label: The issue is not introduced by Phobos or any other engine extension, such as Ares, Kratos etc.
          required: true
        - label: The issue wasn't fixed in the most recent version of Ares/Phobos yet.
          required: true
        - label: I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
          required: true
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search and read the issue list to find a similar issue and didn't find it.
          required: true
        - label: I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Write a detailed description telling us what the issue is, and if/when the bug occurs.
    validations:
      required: true

  - type: textarea
    id: conditions
    attributes:
      label: Conditions to reproduce
      description: |
        For example, used mod, external changes that are used to reproduce the bug.
    validations:
      required: false

  - type: textarea
    id: ini
    attributes:
      label: INI code
      description: The INI code that is used to reproduce the issue.
      render: ini
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Tell us how to reproduce this issue so the developer(s) can reproduce the bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: |
        Tell us what should happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: |
        Tell us what actually happens instead.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Attach additional files or links to content related to the bug report here, like:
        - images/gifs/videos to illustrate the bug;
        - files that are needed to reproduce the bug;
        - a savegame file with used mod to reproduce the exact conditions;
        - a debug log, crash dump and exception file (mandatory if you're submitting a crash report);
        - sync logs, crash dumps for all the players (mandatory in case you're submitting a desync report).