#ifndef VERSION_H
#define VERSION_H

#define _STR(x) _STR_(x)
#define _STR_(x) #x

#pragma region Version numbering

// Indicates project maturity and completeness
#define VERSION_MAJOR 0

// Indicates major changes and significant additions, like new logics
#define VERSION_MINOR 5

// Indicates minor changes, like vanilla bugfixes, unhardcodings or hacks
#define VERSION_REVISION 0

// Indicates Phobos-related bugfixes only
#define VERSION_PATCH 0

// The current pre-release being prepared, spelled out in full rather than as a number, so that
// it can be anything semantic versioning allows - "alpha5", "beta1", "rc3", etc. Its presence is
// what makes a release build a pre-release; comment it out for a stable release.
#define PRERELEASE_SUFFIX "alpha1"

#pragma endregion

#define VERSION_LONG_STR _STR(VERSION_MAJOR) "." _STR(VERSION_MINOR) "." _STR(VERSION_REVISION) "." _STR(VERSION_PATCH)

// Savegame compatibility is tied to the version with the patch number left out: patch releases
// only carry Phobos bugfixes and stay compatible with each other. Nightlies and pre-releases of
// a version share the ID with the stable release they lead up to.
#define SAVEGAME_ID ((VERSION_MAJOR << 24) | (VERSION_MINOR << 16) | (VERSION_REVISION << 8))

// Git info (commit / ref / dirty), generated by Phobos.props' ComputeGitInfo target into $(IntDir)Generated.
#include "Phobos.Git.h"

#pragma region Build metadata

// NIGHTLY / RELEASE come from the BuildType compiler option - used by GH Actions as well - and
// none of them being set means a local build. A pre-release is a RELEASE build that still has
// the PRERELEASE_SUFFIX defined above. STR_GIT_COMMIT / STR_GIT_REF / STR_GIT_DIRTY are
// defined by the generated Phobos.Git.h whenever Git info is available (derived from the
// repository at build time as the full ref, e.g. refs/heads/develop). Pre-releases and
// releases embed
// that info as auxiliary metadata (crash reports, logs, file resources) while keeping a clean
// version string; nightly and local builds carry the Git info in the version itself and differ
// only in the build type name. Everything below is derived from those inputs so that the product
// name, the version and the build type are each spelled out once and stay in sync everywhere they
// surface.

#define PRODUCT_NAME "Phobos"
#define PRODUCT_FILE_NAME PRODUCT_NAME ".dll"
#define PRODUCT_SUMMARY "Ares-compatible YR engine extension"

// The "v" prefix is a human-facing convention for version numbers and is only ever applied in
// front of a numeric version - never in front of a ref or commit. It is applied exactly once
// here in PRODUCT_VERSION and no other macro in this header prepends it.
#define VERSION_PREFIX "v"

// STR_GIT_COMMIT / STR_GIT_REF are defined by the generated Phobos.Git.h when Git info is
// available; STR_GIT_DIRTY falls back to empty when the working tree is clean.
#ifndef STR_GIT_DIRTY
	#define STR_GIT_DIRTY ""
#endif

// The numeric file version is the full four-part version for every build type.
#define FILE_VERSION VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_PATCH

#if defined(RELEASE)
	// A RELEASE build whose PRERELEASE_SUFFIX is still defined is a pre-release;
	// without it, a stable release.
	#ifdef PRERELEASE_SUFFIX
		#define BUILD_TYPE_NAME "pre-release build"
		#define FILE_VERSION_STR VERSION_LONG_STR "-" PRERELEASE_SUFFIX
		#define PRODUCT_VERSION VERSION_PREFIX FILE_VERSION_STR
	#else
		#define BUILD_TYPE_NAME "release build"
		#define FILE_VERSION_STR VERSION_LONG_STR
		#define PRODUCT_VERSION VERSION_PREFIX FILE_VERSION_STR
	#endif
#else
	// Nightly (CI) and local builds are one mostly unified build differing in warning and in
	// build type name; the version string carries the Git commit and ref when available.
	#ifdef NIGHTLY
		#define BUILD_TYPE_NAME "nightly build"
	#else
		#define BUILD_TYPE_NAME "local build"
	#endif
	#ifdef STR_GIT_COMMIT
		#define FILE_VERSION_STR VERSION_LONG_STR "+" STR_GIT_COMMIT STR_GIT_DIRTY
	#else
		#define FILE_VERSION_STR VERSION_LONG_STR
	#endif
	#ifdef STR_GIT_REF
		#define PRODUCT_VERSION VERSION_PREFIX FILE_VERSION_STR " @ " STR_GIT_REF
	#else
		#define PRODUCT_VERSION VERSION_PREFIX FILE_VERSION_STR
	#endif
#endif

// A testing build carries the on-screen "please test the build before shipping" warning and the
// SpecialBuild file flags: everything that is not a stable release - local dev, nightly and
// pre-release builds. A pre-release is a RELEASE build that still has PRERELEASE_SUFFIX defined.
#if !defined(RELEASE) || defined(PRERELEASE_SUFFIX)
	#define TESTING_BUILD
#endif

#define FILE_DESCRIPTION PRODUCT_NAME ", " PRODUCT_SUMMARY " (" BUILD_TYPE_NAME ")"

#pragma endregion

#endif // VERSION_H
