name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -g editorconfig-checker@4.0.2
      - run: editorconfig-checker
