name: Labeler Action
on:
  pull_request_target:
    types: [opened, edited]

jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Label
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
