name: Pull Request Nightly Build

on:
  pull_request:
    # Only build when source code or project/build configuration files change.
    paths:
    - '**/*.c'
    - '**/*.cc'
    - '**/*.cpp'
    - '**/*.cxx'
    - '**/*.h'
    - '**/*.hh'
    - '**/*.hpp'
    - '**/*.hxx'
    - '**/*.inl'
    - '**/*.inc'
    - '**/*.rc'
    - '**/*.sln'
    - '**/*.vcxproj'
    - '**/*.props'
    - '**/*.targets'
    - '.github/**'
    - 'scripts/**'
    - 'YRpp/**'
    - '.gitmodules'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
        # ref: ${{ github.event.pull_request.head.sha }}

    - name: Build Phobos
      uses: ./.github/actions/build-phobos  # Setup steps are reused
      with:
        sln-path: ${{env.SOLUTION_FILE_PATH}}
        build-config: ${{env.BUILD_CONFIGURATION}}
        build-type: NIGHTLY

